// Build the MCP Apps views (see apps/docs/docs/mcp-server/interactive-views.md).
//
// A view is one self-contained HTML document: the host fetches it as a `ui://`
// resource and renders it in a sandboxed iframe with a restrictive CSP, so
// nothing may be pulled in at runtime — no CDN script, no external stylesheet.
// This script bundles views/<name>.js with esbuild and inlines the result into
// views/<name>.html at the `<!-- BUNDLE -->` marker.
//
// The output is committed to src/views/, deliberately. The server has no build
// step of its own: `pnpm dev:mcp` runs src/stdio.js straight from source, the
// .mcpb bundle copies src/ wholesale, and wrangler reads the same file as a Text
// module when the Worker is deployed. Shipping the built HTML keeps all three
// paths working without any of them learning to compile anything.
//
// Run with: pnpm --filter @spelling-creator/mcp build:views

import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(pkgRoot, "views");
const outDir = join(pkgRoot, "src", "views");

const VIEWS = ["imagePicker", "proposalDiff"];
const MARKER = "<!-- BUNDLE -->";

const GENERATED_BANNER =
  "<!-- Generated by scripts/build-views.mjs from views/%NAME%.{html,js} — do not edit. -->";

for (const name of VIEWS) {
  const bundle = await build({
    entryPoints: [join(srcDir, `${name}.js`)],
    bundle: true,
    minify: true,
    format: "iife",
    platform: "browser",
    target: ["es2022"],
    write: false,
  });

  const [output] = bundle.outputFiles;
  const template = readFileSync(join(srcDir, `${name}.html`), "utf8");
  if (!template.includes(MARKER)) {
    throw new Error(
      `views/${name}.html has no ${MARKER} marker to inline into`,
    );
  }

  // No </script> can appear inside the bundle's text or it would close the tag
  // early; esbuild doesn't escape it, so do it here.
  const script = output.text.replace(/<\/script/gi, "<\\/script");
  // Every insertion goes through a replacer function, never a replacement
  // string: minified JS is full of `$&`, `$'` and `` $` `` sequences, and as a
  // replacement string those are substitution patterns — they silently rewrite
  // the bundle into something that no longer parses.
  const html = template
    .replace(MARKER, () => `<script>\n${script}\n</script>`)
    .replace(
      "<!doctype html>",
      () => `<!doctype html>\n${GENERATED_BANNER.replace("%NAME%", name)}`,
    );

  mkdirSync(outDir, { recursive: true });
  const outFile = join(outDir, `${name}.html`);
  writeFileSync(outFile, html);
  const kb = (Buffer.byteLength(html) / 1024).toFixed(1);
  console.log(`views: ${name}.html (${kb} kB)`);
}
